project_id = "ingyimnrogaxulfvlubg"

[functions.api-query]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.mcp-server]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.generate-blog-post]
verify_jwt = false

[functions.tts-blog]
verify_jwt = false
